#!/bin/sh

template_header='template_header.txt'

decl_template='declarative_template.txt'
decl_output='test_declarative.html'

script_template_1='script_template.txt'
script_output_1='test_script.html'

script_template_2='script_2_template.txt'
script_template_2_end='script_2b_template.txt'
script_output_2='test_script_2.html'

#num_copies=10
num_copies=10000

function write_header() {
  sed -e "s/\${num_copies}/${num_copies}/" ${template_header} > $1
}

function write_footer() {
  cat <<EOF >>$1
    </div> <!-- id=suppress_layout -->
EOF
}

function write_copies() {
  for (( i=0; i<${num_copies}; i++ )); do
    sed -e "s/\${copy_num}/${i}/" $1 >> $2
  done
}

echo "Writing ${decl_output}..."
write_header ${decl_output}
write_copies ${decl_template} ${decl_output}
write_footer ${decl_output}

echo "Writing ${script_output_1}..."
write_header ${script_output_1}
write_copies ${script_template_1} ${script_output_1}
write_footer ${script_output_1}

echo "Writing ${script_output_2}..."
write_header ${script_output_2}
write_copies ${script_template_2} ${script_output_2}
write_footer ${script_output_2}
cat ${script_template_2_end} >> ${script_output_2}

